### ISSUE TITLE
debug 方面的几个问题

### ISSUE THREAD

**Issue by GvcZhang** [fightcoder/ftd#1]
您好，关于debug有几个问题，请教一下，如下：
1. `starter.dart`中修改被注释的`args`参数，修改结果如下，应该就是需要这些参数才能调试吧？
```dart
void main(List<String> args) async {

  ///debug
 List<String> ss = [];
 ss.add('--sdk-root');
 ss.add('/Users/zhangwei/Documents/tools/flutter');
 ss.add('--target=flutter');
 ss.add('-Ddart.developer.causal_async_stacks=true');
 ss.add('-Ddart.vm.profile=false');
 ss.add('-Ddart.vm.product=false');
 ss.add('--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions');
 ss.add('--enable-asserts');
 ss.add('--track-widget-creation');
 ss.add('--no-link-platform');
 ss.add('--packages');
 ss.add('/Users/zhangwei/Documents/work/flutter_workspace/ftd/example/.packages');
 ss.add('--output-dill');
 ss.add('/Users/zhangwei/Documents/work/flutter_workspace/ftd/example/.dart_tool/flutter_build/183811f45d9515a332c9d786ce99db6c/app.dill');
 ss.add('--depfile');
 ss.add('/Users/zhangwei/Documents/work/flutter_workspace/ftd/example/.dart_tool/flutter_build/183811f45d9515a332c9d786ce99db6c/kernel_snapshot.d');
 ss.add('package:example/main.dart');

  final int exitCode = await starter(args);
  if (exitCode != 0) {
    exit(exitCode);
  }
}
```

2.项目中很多文件报红，导致 debug 的时候(直接右键 debug starter.dart 文件)报错，如下图所示  
![image](https://user-images.githubusercontent.com/45255699/103163116-ae9dab80-4834-11eb-9404-fc29bd428344.png)

这个报错，我看`pubspec.yaml`中有指定`front_end`等配置，需要指定本地的吗？
![image](https://user-images.githubusercontent.com/45255699/103163171-70ed5280-4835-11eb-87b8-de885868db1d.png)

**Comment by fightcoder** [comment]
> 您好，关于debug有几个问题，请教一下，如下：
> 
> 1. `starter.dart`中修改被注释的`args`参数，修改结果如下，应该就是需要这些参数才能调试吧？
> 
> ```dart
> void main(List<String> args) async {
> 
>   ///debug
>  List<String> ss = [];
>  ss.add('--sdk-root');
>  ss.add('/Users/zhangwei/Documents/tools/flutter');
>  ss.add('--target=flutter');
>  ss.add('-Ddart.developer.causal_async_stacks=true');
>  ss.add('-Ddart.vm.profile=false');
>  ss.add('-Ddart.vm.product=false');
>  ss.add('--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions');
>  ss.add('--enable-asserts');
>  ss.add('--track-widget-creation');
>  ss.add('--no-link-platform');
>  ss.add('--packages');
>  ss.add('/Users/zhangwei/Documents/work/flutter_workspace/ftd/example/.packages');
>  ss.add('--output-dill');
>  ss.add('/Users/zhangwei/Documents/work/flutter_workspace/ftd/example/.dart_tool/flutter_build/183811f45d9515a332c9d786ce99db6c/app.dill');
>  ss.add('--depfile');
>  ss.add('/Users/zhangwei/Documents/work/flutter_workspace/ftd/example/.dart_tool/flutter_build/183811f45d9515a332c9d786ce99db6c/kernel_snapshot.d');
>  ss.add('package:example/main.dart');
> 
>   final int exitCode = await starter(args);
>   if (exitCode != 0) {
>     exit(exitCode);
>   }
> }
> ```
> 
> 2.项目中很多文件报红，导致 debug 的时候(直接右键 debug starter.dart 文件)报错，如下图所示
> ![image](https://user-images.githubusercontent.com/45255699/103163116-ae9dab80-4834-11eb-9404-fc29bd428344.png)
> 
> 这个报错，我看`pubspec.yaml`中有指定`front_end`等配置，需要指定本地的吗？
> ![image](https://user-images.githubusercontent.com/45255699/103163171-70ed5280-4835-11eb-87b8-de885868db1d.png)

`dependency_overrides`中配置完整即可，
![image](https://user-images.githubusercontent.com/19933500/103184195-d56de780-48f1-11eb-8cea-60333d9ecd91.png)

**Comment by GvcZhang** [comment]
感谢 wangzi 大佬，我这边测试可以的。
wangzi 大佬，帮忙看一下这个问题哈~：https://github.com/fightcoder/ftd/issues/2
