### ISSUE TITLE
dill_transfom.dart 中的代码如何调试

### ISSUE THREAD

**Issue by GvcZhang** [fightcoder/ftd#2]
wangzi 大佬，咨询一下 `runBuildDillCommand`方法该如何调试，调试 flutter-tools 并在此位置打断点没有执行到这边，期望回答，谢谢。

**Comment by fightcoder** [comment]
> wangzi 大佬，咨询一下 `runBuildDillCommand`方法该如何调试，调试 flutter-tools 并在此位置打断点没有执行到这边，期望回答，谢谢。

这里没什么，就是检测下是否有依赖，处理依赖，处理dill和snapshot，你要看可以通过日志调试即可

**Comment by GvcZhang** [comment]
打日志的话我有想过，不过有点太麻烦了，我发现修改以后必须得删除 flutter_tools.stamp 重新生成 snapshot 才能起作用，后面也是直接执行 snapshot，所以才不会走到这边吗？

**Comment by GvcZhang** [comment]
目前一直在看 flutter-tools 这块的逻辑，我还没有get到那个点

**Comment by fightcoder** [comment]
> 打日志的话我有想过，不过有点太麻烦了，我发现修改以后必须得删除 flutter_tools.stamp 重新生成 snapshot 才能起作用，后面也是直接执行 snapshot，所以才不会走到这边吗？

因为执行的是构建后的snapshot，这里在`bin/internel/shared.sh`
